FROM php:8.2-fpm

# Installer les dépendances système
RUN apt-get update && apt-get install -y \
    git curl zip unzip \
    libpng-dev libjpeg-dev libfreetype6-dev \
    libonig-dev libxml2-dev

# Extensions PHP nécessaires pour Laravel
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Créer le dossier de travail
WORKDIR /var/www

# Copier d'abord composer.json pour optimiser le cache
COPY composer.json composer.lock ./

# Installer les dépendances PHP
RUN composer install --no-dev --no-scripts --no-progress --no-interaction || true

# Copier tout le reste du projet Laravel
COPY . .

# Installer les dépendances nécessaires à ext-zip
RUN apt-get update && apt-get install -y \
    libzip-dev zip unzip \
    && docker-php-ext-install zip


# Exécuter à nouveau composer (cette fois avec les scripts)
RUN composer install --optimize-autoloader --no-interaction

# Donner les permissions à Laravel
RUN chown -R www-data:www-data /var/www \
    && chmod -R 755 /var/www/storage \
    && chmod -R 755 /var/www/bootstrap/cache

CMD ["php-fpm"]
